### ISSUE TITLE
[Bug]: 绅士漫画问题

### ISSUE THREAD

**Issue by vjfVbOnXPVX8HCP** [Pacalini/PicaComic#21]
### 描述/Description

图片加载错误

### Version

4.13

### 使用的操作系统/Operating system

Android

### 日志/logs

DioException [unknown]: Connection terminated during handshake: This may be caused by the firewall blocking the connection or your requests are too frequent.
Error: HandshakeException: Connection terminated during handshake
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:510)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _FutureListener.handleError (dart:async/future_impl.dart:181)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873)
#5      Future._propagateToListeners (dart:async/future_impl.dart:894)
#6      Future._completeError (dart:async/future_impl.dart:674)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      Future.any.onError (dart:async/future.dart:633)
#10     _rootRunBinary (dart:async/zone.dart:1423)
#11     _CustomZone.runBinary (dart:async/zone.dart:1315)
#12     _FutureListener.handleError (dart:async/future_impl.dart:178)
#13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:873)
#14     Future._propagateToListeners (dart:async/future_impl.dart:894)
#15     Future._completeError (dart:async/future_impl.dart:674)
#16     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:564)
#17     _rootRun (dart:async/zone.dart:1399)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

**Comment by vjfVbOnXPVX8HCP** [comment]
![Screenshot_2024-10-28-12-28-11-677_com github pacalini pica_comic](https://github.com/user-attachments/assets/d01c8d14-5039-4c90-a437-7c33da849d5a)

**Comment by vjfVbOnXPVX8HCP** [comment]
浏览器网站显示正常
![Screenshot_2024-10-28-12-30-04-172_mark via gp](https://github.com/user-attachments/assets/f21086d2-7ffe-4324-8ee0-94c0dd4fecfb)
